Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: '!ImportValue VpcId'
  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Default: '!ImportValue PrivateSubnet1Id'
  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Default: '!ImportValue PrivateSubnet2Id'
  ClusterName:
    Type: String
    Default: '!ImportValue ClusterName'
  DotNetAppTargetGroup:
    Type: String
    Default: '!ImportValue DotNetAppTargetGroup'
  DotNetAppALBSecurityGroup:
    Type: Stting
    Default: '!ImportValue DotNetAppALBSecurityGroup'
  

Resources:
  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and port 8080 access to cluser
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref DotNetAppALBSecurityGroup

  DotNetECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      ServiceName: DotNetECSService
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ClusterSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1Id
            - !Ref PrivateSubnet2Id
            - !Ref PrivateSubnet3Id
      LoadBalancers:
        - ContainerName: Service1
          ContainerPort: 8081
          TargetGroupArn: !Ref DotNetAppTargetGroup
      DesiredCount: 3
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      TaskDefinition: !Ref TDService1

  DotNetECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 4096
      Memory: 8192
      Family: DotNetECSService
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      RuntimePlatform:
          CpuArchitecture: X86_64
          OperatingSystemFamily: WINDOWS_SERVER_2022_FULL
      TaskRoleArn: #TaskRole
      ExecutionRoleArn: #ExecutionRole
      ContainerDefinitions:
        - Name: DotNetECSService
          Image: arn:aws:ecr:ap-southeast-1:xxxxxxxxxxxx:dotnetapp/salesappapi:latest
          Essential: true
          Cpu: 2048
          Memory: 4096
          PortMappings:
            - HostPort: 8081
              ContainerPort: 8081
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/salesappapi
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
