AWSTemplateFormatVersion: '2010-09-09'
Description: 'DotNetApp Production'

Parameters:
  CfnS3Bucket:
    Type: String
    Default: #S3 BucketName
    Description: S3 bucket name of the cloudformation template located.
  EnvironmentName:
    Type: String
    Default: #EnvironmentName

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: #Template URL

  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: #Template URL

  ECSServiceStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: #Template URL
      Parameters:
        ClusterName: !GetAtt 'ECSClusterStack.Outputs.ClusterName'
        VpcId: !GetAtt 'VpcStack.Outputs.VpcId'
        PrivateSubnet1Id: !GetAtt 'VpcStack.Outputs.PrivateSubnet1Id'
        PrivateSubnet2Id: !GetAtt 'VpcStack.Outputs.PrivateSubnet2Id'
        DotNetAppTargetGroup: !GetAtt 'ECSALBStack.Outputs.DotNetAppTargetGroup'
        DotNetAppALBSecurityGroup: !GetAtt 'ECSALBStack.Outputs.DotNetAppALBSecurityGroup'
        DotNetAppLoadBalancer: !GetAtt 'ECSALBStack.Outputs.DotNetAppLoadBalancer'

  ECSALBStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: #Template URL
      Parameters:
        VpcId: !GetAtt 'VpcStack.Outputs.VpcId'
        PublicSubnet1Id: !GetAtt 'VpcStack.Outputs.PublicSubnet1Id'
        PublicSubnet2Id: !GetAtt 'VpcStack.Outputs.PublicSubnet2Id'
        PrivateSubnet1Id: !GetAtt 'VpcStack.Outputs.PrivateSubnet1Id'
        PrivateSubnet2Id: !GetAtt 'VpcStack.Outputs.PrivateSubnet2Id'
        PublicSubnet1Az: !GetAtt 'VpcStack.Outputs.PublicSubnet1Az'
        PublicSubnet2Az: !GetAtt 'VpcStack.Outputs.PublicSubnet2Az'
        PrivateSubnet1Az: !GetAtt 'VpcStack.Outputs.PrivateSubnet1Az'
        PrivateSubnet2Az: !GetAtt 'VpcStack.Outputs.PrivateSubnet2Az'
