AWSTemplateFormatVersion: "2010-09-09"
Description: DotNetApp-Fargate

Parameters:
  ClusterName:
    Type: String
    Default: DotNetApp-Cluster

Resources:
  DotNetAppCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      ServiceConnectDefaults:
        Namespace: #NameSpace
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1

Outputs:
  ClusterName:
    Description: The ClusterName of the ECS cluster
    Value: !Ref ClusterName
    Export:
      Name: ClusterName